language: java
jdk:
- oraclejdk7
- openjdk7
after_script:
- cd ..
- ./scripts/s3upload.sh
env:
  global:
  - S3_POLICY: ewogICJleHBpcmF0aW9uIjogIjIxMDAtMDEtMDFUMTI6MDA6MDAuMDAwWiIsCiAgImNvbmRpdGlvbnMiOiBbCiAgICB7ImFjbCI6ICJwdWJsaWMtcmVhZCIgfSwKICAgIHsiYnVja2V0IjogInNlbmRncmlkLW9wZW4tc291cmNlIiB9LAogICAgWyJzdGFydHMtd2l0aCIsICIka2V5IiwgInNtdHBhcGktamF2YS8iXSwKICAgIFsiY29udGVudC1sZW5ndGgtcmFuZ2UiLCAyMDQ4LCAyNjg0MzU0NTZdLAogICAgWyJlcSIsICIkQ29udGVudC1UeXBlIiwgImFwcGxpY2F0aW9uL3ppcCJdCiAgXQp9Cg==
  - secure: mmr0NIQtQNnzMXPDN4YRBh8/NZX5FuPYlcrD/iZGMtEYKlXcmKziCzVu/XAvMGYPaeM0TCMSreWX2cD6KfFfcXQOtEoQGjngqHYWYjO9H3FwkUKJhjAEPqkAiI/kc5A9RMoM66eQvEcQ03mwyrXz3Xsuy826mKBUyMBcIvX0D/I=
  - secure: aqXQn+NgNXEXL1GgzZP2+pqr0SVffAo6UZs4Tdu1l3eOVUhddAXpM3wZDqQpOMF1UfVCyIOymYTertVwFg9STMnnJHVy/lcRkG2E1w0bcs2S/goZtWGpr94EvIhm3ESw0rszkZLKgvbDnGQRd5/rqgRAqNq/aJnPnmocP+YfsQ0=
  - secure: Z0ivY2rTHZaD/30+2Ta4UrFIjSro6epw+w3Ufu74YzTT3UcTIIb8zhNoMlcwZjTEtJu1IkDQljR3kYg3/1Gx3qZUwo98eq7TVVh+ozzQTcWu8lKz4+vIduS04mZTAZgEDuntkP86yGOfeRRezlG9LYuWmiQfMlOR4wZvjfYjPAk=
